### ISSUE TITLE
Cannot open on manjaro

### ISSUE THREAD

**Issue by chowder3907** [SuperPou1/sm64pclauncher#4]
The program does not open after running launcher.py. I have the latest python installed and ran the dependencies script. Here is the terminal output
![image](https://user-images.githubusercontent.com/63274355/128822507-29004cca-03bf-4ab8-b219-a33bada325ea.png)

**Comment by SuperPou1** [comment]
You are running it the wrong way. You tried to run launcher as a bash script I see, you are supposed to run it like that: `python3 launcher.py`
